# Generated by Django 3.1.2 on 2020-11-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_name', models.CharField(max_length=64)),
                ('pd_type', models.CharField(max_length=64)),
                ('pd_cost', models.IntegerField(default=0)),
                ('pd_count', models.IntegerField(default=0)),
            ],
        ),
    ]
