# Generated by Django 3.1.2 on 2020-11-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pd_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
